### ISSUE TITLE
FAQ page

### ISSUE THREAD

**Issue by TobiGr** [TeamNewPipe/website#69] opened 2018-04-15 08:48 UTC
As already discussed before we need a place to explain features a little further. We collected some potential Q&As and tutorials in TeamNewPipe/NewPipe#1316:

- how to open up the background player queue from notification (though this should be part of the tutorial)
- downloading on sdcard is not functional and is in the works right now
- what's new / feed is currently experimental and is in the works right now
- age-gated video will produce an error snackbar on video details fragment 
- auto-play toggle
- how to switch between players
- how to search and play SoundCloud streams
- open stream options with a longpress on the stream item in a list
- longpress on background / popup buttons to enqueue stream
- import / export subscriptions
- import / export app data (history, ...)
- swipe to left/right to close popup player
- resize popup player
- comment support on our todo-list
- no Google login

Nevertheless we should introduce new features for each new version in a detailed blog post.

I'll come up with a nice design soon.

**Comment by TheAssassin** [comment] 2018-04-15 12:59
Great idea. Thanks for taking care of this, @TobiGr.

**Comment by TobiGr** [comment] 2018-04-16 18:42
I added some more interesting points and put them into categories. Does the grouping make sense to you? Should any items be removed? @theScrabi @TheAssassin @karyogamy @mauriciocolli @wb9688 
Some things appear twice on the list which is not perfect, but I personally would search for them in both categories.

## Player 

### Player handling 

-    Switch between players 
-    Resize popup 
-    Close popup 
-    Open background player from notification 

### Player enhancements 

-    Enable autoplay 
-    Enqueue on longpress
-    Enable subtitles

## Import / Export / Download 

-    Subscriptions 
-    App database 
-    Sd card 
-    Audio missing streams 
-    MP3 download 


## Known bugs / Can you please implement …? 

-    SDcard 
-    Audio missing streams 
-    MP3 download 
-    SoundCloud 
-    YouTube feed / What's New 
-    Google login 
-    YouTube comments

**Comment by TobiGr** [comment] 2018-04-21 17:36
I basically planned two different page types:

**a) The FAQ & Tutorials landing page**
From here you can get to one of the three sub-sites. I think a search could be helpful too.

![getimage 1](https://user-images.githubusercontent.com/17365767/39086964-60db80c0-4599-11e8-9fa5-3f2048ec69f2.png)

 **b) The sub-sites with the tutorials**
Initially the texts should be collapsed to offer a clean UI.  Clicking on a title unfolds the content. This is quite handy for mobiles too. 

![getimage](https://user-images.githubusercontent.com/17365767/39086872-19268d42-4599-11e8-8cb2-2fa2fa6bac51.png)

When there are no objections, I'd start to implement this. This will take some time since we have beautiful weather in Germany right now ;)

**Comment by theScrabi** [comment] 2018-04-21 17:39
I like the second one.

> This will take some time since we have beautiful weather in Germany right now ;)

Joy it :D We get fried like egs in the pan down here in Spain.

**Comment by karyogamy** [comment] 2018-04-21 18:01
Looks awesome =D

**Comment by TheAssassin** [comment] 2018-04-21 19:11
Great work as usual.

**Comment by princekelly1** [comment] 2018-10-19 12:33
Am planning on writing, the FAQ in this way. 
* Getting started on Newpipe
This will consist of the following. 
Description of the app's homepage features, briefly. And picking each category for further explanations

**Comment by princekelly1** [comment] 2018-10-19 12:37
I will send a document, once I compile the ideas.

**Comment by princekelly1** [comment] 2018-10-20 05:55
Below, I have made a draft suitable for use on the project's github profile. Which can easily be adapted to the app's website.
If you like this draft. I will keep working on the template i created.
I await your reply.


# New Pipe FAQs
## What is New pipe
Newpipe is a lightweight Youtube frontend, created for users to enjoy the original Youtube experience on their mobile device, without annoying ads and questionable permissions. With Newpipe users can download their favorite videos without expiration limits. And can share their downloaded videos to friends.

## Getting started on NewPipe
How you navigate through **NewPipe** depends on your selected video sharing app. New pipe offer users the option, to use Youtube and Soundcloud.
On your Newpipe app, look at the top left of your screen, to see your selected video sharing app. You can click on it, to choose between Youtube and Soundcloud.

## Newpipe Homepage
The Newpipe apps consist of the following main features
*Trending.
* Subscription.
* Bookmarks.
* Download.
* History.
* Settings.
* About.

<center><h2> Trending</h2><center>

The trending section of Newpipe displays, the most popular videos from Youtube at the moment. It displays a random selection of popular videos, depending on your preferred content country. The default content country on your Newpipe is the **United Kingdom**. To change your default content country, please refer to the content section under the settings guide in this FAQ document.
<center><h2> Subscription</h2><center>
This tab shows you, the list of your subscribed channels. Tap on a channel to view the list of videos on the channel.
### Import/Export
You can use this option to import and export channels from Youtube and Soundcloud.
1.  **To Import Subscription**: Tap on the import/export button, Select either Youtube or SoundCloud.
*For Youtube:
i. Go to this URL: https://www.youtube.com/subscription_manager?action_takeout=1
ii.  Log in if asked.
iii.  A download will start (that’s the export file from your Youtube profile).
iv.  Go back to your Newpipe app, and tap on the **import file** at the bottom of the page. Now, select your downloaded Youtube export file.
*For SoundCloud:
i.  Go to this URL: https://soundcloud.com/you, on a web browser (Make sure to enable desktop mode).
ii.  Log in when asked.
iii.  Copy the profile URL, you were directed to.
iv.  Go back to your Newpipe app and paste the URL in the space provided. Tap **import** at the bottom of the page.

2.  **Import from previous export**: Tap on **previous export**, to select from your previous exported files.

3.  **Export to**: This allows users to create a Json file, of their Youtube/SoundCloud subscriptions and save on their device.

**Comment by TobiGr** [comment] 2018-10-23 09:36
@princekelly1 Thanks for writing some new FAQs. 👍 The subscriptions tutorial is really helpful. I'll implement it soon after the new app release. I'd like to change the trending FAQ a bit to start a new collection for the getting started page. 

@TheAssassin @theScrabi @princekelly1 @saderror256 This is how I'd like to include and announce the FAQ page on the home page. Is there something missing which needs to be there?

Are there any tutorials which should be there instead of the _save mobile data_ box? e.g. switch between players or import subscriptions. Which tutorials do you prefer to display on the main page?

As you can see, we need an additional tutorial on how to **enable unknown sources and install NewPipe** properly. 


![img_20181023_111623_2](https://user-images.githubusercontent.com/17365767/47350688-ad055580-d6b6-11e8-911f-9640610d21ec.jpg)

**Comment by princekelly1** [comment] 2018-10-23 10:54
My pleasure.
Import subscription should be displayed in the tutorial box.

**Comment by princekelly1** [comment] 2018-10-23 10:56
I can create a tutorial on how to **enable unknown source" to install the app.

**Comment by princekelly1** [comment] 2018-10-23 18:01
# How to enable the unknown source to install NewPipe on your device

**First method**: Open your device settings. Then locate and open **security settings**, you should see an option **Unknown sources**. Activate it to allow installation of apps from unknown sources. Then you can download your Newpipe app and install successfully on your device.

**Second Method**: If you have downloaded the Newpipe app, and on installing, you get a message, **For security, your phone is set to block installation of apps obtained from unknown sources**. Click settings, and locate **Unknown Sources**, activate it. Go back to your installation and your app will be installed successfully on your device.

**Comment by manoelnascimento** [comment] 2019-04-02 14:43
If you accept a suggestion, I think there should be a page to deal with application errors. In my case, for example, the application always failed to import YouTube subscription files. With SondCloud it works fine, but with YouTube the import always gives error messages. I tried to research something on the subject, but there does not seem to be anything available on the internet that deals with such issues. (Translated by Google Translator)

**Comment by rugk** [comment] 2019-09-24 21:29
BTW remember that this "unknown sources" handling changed with Android 9 (or Android 8?). This needs to be accounted for in the FAQ.

**Comment by B0pol** [comment] 2020-01-14 11:22
About comments, it's now in the app, but no comment replies
Then we should update this section
![image](https://user-images.githubusercontent.com/58657617/72340450-258f7200-36c0-11ea-9c0a-b7e69a4c3d88.png)

**Comment by TobiGr** [comment] 2020-01-14 13:36
@B0pol Thanks! What about this:
![image](https://user-images.githubusercontent.com/17365767/72348689-38637000-36db-11ea-9a25-236f196a07c9.png)

**Comment by B0pol** [comment] 2020-01-14 13:39
Looks perfect to me

**Comment by denterwiser** [comment] 2020-04-15 18:30
Hi everyone.

Excuse me if this is the wrong place to write a suggestion, but could you please include in the FAQ a section on privacy? I know your privacy policy discusses what _you_ may collect, but I think it would be extremely helpful to write something similar to what I see on the Invidio.us site where they also point us to the googlevideo.com's privacy policy as they link directly to videos on their servers: https://invidio.us/privacy

> This website provides links to googlevideo.com to provide audio and video playback. googlevideo.com is owned by Google and is subject to their privacy policy.

This way we can all make an informed decision if some of the content you link to has my device directly connecting to YouTube's servers.

I would write this myself, but I am not a coder so I don't know how.

Thanks for the great app looking forward to seeing further development.

**Comment by TheAssassin** [comment] 2020-04-15 18:35
Very good idea. Our own privacy policy also requires a link on the third party services' privacy policies. But an FAQ entry is surely helpful, too.

**Comment by Poolitzer** [comment] 2020-04-17 01:55
I will write smth together

**Comment by panther7** [comment] 2020-11-15 10:39
Hi, export youtube subscription doesn't works by tutorial: https://newpipe.schabi.org/FAQ/tutorials/import-export-data/#import-youtube

**Comment by denilsonsa** [comment] 2020-12-04 18:19
"[Export and backup all NewPipe data](https://newpipe.schabi.org/FAQ/tutorials/import-export-data/#export-database)" sounds like it will preserve both the subscriptions, history and playlists; and also all the settings.

However, the text in the paragraph doesn't mention if the settings are preserved or not. It would be clearer if this FAQ entry were explicit about it. (Just like it is already explicit about *"not only your subscriptions, but also your search and watch history (...) and local playlists"*. So, include settings in this sentence, or add another sentence explaining what is NOT backed up.)

**Comment by ChrisJr4Eva87** [comment] 2021-02-20 10:45
C x

**Comment by lizardson79** [comment] 2021-05-10 07:13
If this app has widget(audio only) on home screen, it will be god like app.

**Comment by opusforlife2** [comment] 2021-05-10 20:07
@lizardson79 This is the repo for the NewPipe website, not the app. Please comment in the correct repo.

**Comment by yashpalgoyal1304** [comment] 2021-05-14 15:34
hi, i think that in this page [adding repo](https://newpipe.net/FAQ/tutorials/install-add-fdroid-repo/) [..](https://github.com/TeamNewPipe/website/blob/master/_tutorials/install-add-fdroid-repo.html) - those 2 parts can be merged.

**Comment by yashpalgoyal1304** [comment] 2021-12-07 10:18
hi @Poolitzer , i totally forgot about that.

yeah, so, what i want to say can't be illustrated as such. i though to show it in a diff itself, but html is not smth i feel very confident editing on my own. so... amh, also, i have 2 doubts regarding first method.

1. how will u scan the qr code?
2. and clicking the link does nothing either.

To make either of this work, i have to use external apps. Is that intended? 
* either the [qr code scanner](https://www.f-droid.org/packages/com.example.barcodescanner/)
* or the [Open Link with](https://f-droid.org/packages/com.tasomaniac.openwith.floss/) app

Solving these doubts can maybe provide me with some insight on how can i better get my point across

**Comment by yashpalgoyal1304** [comment] 2021-12-07 10:29
oh, and also, the highlighted portion below is not shown in the automatic section. but these steps still apply there. so, why are they not shown in on there?

![vivaldi_OvFXQ2T4ix](https://user-images.githubusercontent.com/19423063/145012372-41c2f6c0-5b35-4aee-a5bc-4d9b38873f53.png)

shall i open this in a separate issue and move over the discussion there?

**Comment by rodcpanel** [comment] 2022-04-07 20:58
I have uninstalled NewPipe after years of use. It is too unreliable.

Worked for years okay. Last week version 0.22.1 on my Android 11 Samsung tablet stopped working 'unable to parse website'. Deleted app, reinstalled latest version, now it can parse website, I am able to watch/listen in app but unable to download any files because NewPipe now refuses to recognise any of my file managers although it could last week. Prompts me to install a scoped storage file manager - all of my managers are Android 11+ compatible.

Thirty minutes ago, I installed 0.22.1 on my Samsung Android 12 phone. Was able to 'parse website', was able to download one audio file, everything normal. Ten minutes later tried to re-use the app and error message 'unable to resolve host "suggestqueries.google.com" '. Turned off all vpn and privacy/security settings to see it that helped. Nope app still screwing up and for no good reason. 

When it was working it was okay but it always infuriated me that I was forced to look at 'trending' when opening the app. Could not turn it off. Just sickening dross. It is mind rape. 

I will look for an alternative to NewPipe. But disappointed because it was basically a great app and helped me go google-free back when I installed custom rom on my old Nexus 7 tablet. Happy days. No more. Nothing last for ever.

**Comment by yashpalgoyal1304** [comment] 2022-04-08 01:16
(i cant say the exact names, 'cz i dont use en(glish). that's why i am
including item number)

1. Settings
2. Contents (Globe icon, 5th item)
3. Main Page Content (4th item)
4. Bring "Blank Page" to top by tap and dragging the "burger" button

rodcpanel wrote:

> ... forced to look at 'trending' when opening the app. Could not turn it
> off. .
>

**Comment by Rina-Silver** [comment] 2022-05-20 18:44
in the background player, the volume decreases when a notification arrives, but does not automatically increase back.

**Comment by dasapa4746** [comment] 2022-05-27 20:42
Hi! this is a suggestion about suggestions. I created an account to make some feature suggestions on here but have no idea how to do it, if I should use all tags or just enhancement, etc. went looking at the faq and landed here but no tutorial So the extra suggestion is a tutorial on how to post feature requests, and bugs as well if you have he time for those of us that have 0 coding experience aside from installing an unknown source apk

**Comment by Ibiza2004** [comment] 2022-08-12 15:52
Hello 👋 i made an export file of youtube from Google takeout.when i tried to select there were not such options like select subscription only or something.and that exported zip file still now rotting in my phone.I tried to import it to Newpipe numerous times but it was failed.

And now Newpipe isn't working what to do??

**Comment by ctd42** [comment] 2022-08-15 11:18
Ich möchte NewPipe auf Chromebook Acer Spin 513 installieren. Kann ich dafür das aktuelle Release 0.23.2 verwenden – und wie muss ich vorgehen? 
Bin 80 und unerfahren. Habe Linux-Entwicklungsumgebung eingerichtet und würde APK im Linux files directory speichern.

**Comment by epbrown2004** [comment] 2022-11-01 16:19
All subscribed sights are loading blank

**Comment by goyalyashpal** [comment] 2023-03-29 02:00
I think it should be added at the top in the description:

---

```
#################### 
This issue is NOT for posting noob FAQs.
Do NOT post here unless you are familiar 
with culture at issue trackers!!
#################### 
```

**Comment by goyalyashpal** [comment] 2023-03-29 15:48
.... umh, but having an extra measure won't hurt?

**Comment by goyalyashpal** [comment] 2023-03-29 17:41
ohkay, at least unhide this last one lol: https://github.com/TeamNewPipe/website/issues/69#issuecomment-1487839998

**Comment by fernanrouse** [comment] 2023-08-28 15:24
COMMANDS DO NOT WORK IN LOCK MODE iOS
I would like to comment that when you lock the phone and the play command screen is displayed, it locks and in order to continue playing songs automatically, you must unlock the phone at the end of each song. To restore the function, you must restart the application.

**Comment by SharktheNerd** [comment] 2023-12-10 14:01
Hey, guys! I love the app!

Is it able to play YT playlists and stay in the playlist?
Mine keeps randomizing to other ("related") content after the 1st video in a playlist.

If there's a setting I can change, please let me know.

Thanks, 
Sean Kraft

**Comment by SharktheNerd** [comment] 2023-12-10 14:06
> Hey, guys! I love the app!
> 
> Is it able to play YT playlists and stay in the playlist? Mine keeps randomizing to other ("related") content after the 1st video in a playlist.
> 
> If there's a setting I can change, please let me know.
> 
> Thanks, Sean Kraft

I turned off the "auto-enqueuing" option and it seems to be playing playlists uninterrupted.

**Comment by RoadToGlasfaser** [comment] 2023-12-25 20:52
Hi, 
there is no bug report button. Nether in the Website nor in the App. I have double checked on 2 devices. 
The FAQ tells you to come here in case something is missing. Since the last big comment is an "do not FAQ" I think there is an communication problem. 

In case you want bug reports read further:

The wrong info is shown underneath a video I'm watching.

Step by step creation:
1. Reload follow page
2. Have 1 new video
3. Click it
4. Go on full screen
5. Watch the full length
6. Minimise the video to bottom of screen
7. Browse the trends
8. Scroll a bit
9. Click a video
10. Check the info
11. Info of the last video is still showing

**Comment by Rosee220** [comment] 2024-06-13 12:50
I have a problem with NewPipe, when i am watching specific videos, the app is skipping seconds a lot, what i mean is, that it skips every 4 seconds like about 2 seconds, so i don't understand anything the people are saying in the video. That is super annoying and i don't understand why. I can't watch for example 0:01-0:12, then i can watch again 3 seconds and the next 5 seconds are gone. Somebody please help me

**Comment by rugk** [comment] 2024-06-13 22:20
BTW does this issue even need to stay open (and atttrackt people posting off topic stuff here)? After all the FAQ is there for quite a time and it looks solid.

So what is still missing/the reason for keeping this issue open?

**Comment by TheAssassin** [comment] 2024-06-13 22:58
Closing for now, thanks for the hint.

**Closed by TheAssassin** 2024-06-13 22:58 UTC

**Comment by standme321** [comment] 2024-06-23 16:36
I downloaded newpipe on Android TV and I cannot make it full screen. It says an error has occurred, check the notification. 

I can't find the notification on Android TV.

**Comment by Feifel81** [comment] 2024-07-09 18:14
Only some live videos play at the moment like https://www.youtube.com/watch?v=50AkYnMPy2Q

**Comment by pacofuentesuno** [comment] 2024-07-10 04:27
No reproduce ningún video, se cuelga y da error
