### ISSUE TITLE
Playlists shown on channels

### ISSUE THREAD

**Issue by ArtfulAbyss** [TeamNewPipe/website#113] opened 2019-02-23 14:47 UTC
I have a lot of playlists that I like that don't come up on the search engine no matter what I try looking up. I suggest that being able to see the playlists that a user has made on their channel. It would make searching for playlists much easier. Thank you! <3

**Comment by TheAssassin** [comment] 2019-02-23 15:04
This should probably go into the main NewPipe repository, shouldn't it, @ArtfulAbyss? I can transfer the issue if that's the case.

**Comment by TobiGr** [comment] 2019-02-23 18:16
Yep, this should be moved to the app repository. But it's a duplicate of https://github.com/TeamNewPipe/NewPipe/issues/1030
Therefore I'll close this ticket.

**Closed by TobiGr** 2019-02-23 18:16 UTC

**Comment by TheAssassin** [comment] 2019-02-23 19:13
Thanks for confirming. Let's still transfer this one so it's in the right spot.
